import exteriorDayImg from "@/assets/moksha-exterior-day.png";
import roomWindowImg from "@/assets/moksha-room-window.png";
import roomWarmImg from "@/assets/moksha-room-warm.png";
import cottagesNightImg from "@/assets/moksha-cottages-night.png";
import foodSunsetImg from "@/assets/moksha-food-sunset.png";
import viewSignImg from "@/assets/moksha-view-sign.png";
import breakfastViewImg from "@/assets/moksha-breakfast-view.png";
import roomMasterImg from "@/assets/moksha-room-master.png";
import bathroomImg from "@/assets/moksha-bathroom.png";
import mountainCloudsImg from "@/assets/moksha-mountain-clouds.png";

export const exteriorDay = exteriorDayImg;
export const roomWindow = roomWindowImg;
export const roomWarm = roomWarmImg;
export const cottagesNight = cottagesNightImg;
export const foodSunset = foodSunsetImg;
export const viewSign = viewSignImg;
export const breakfastView = breakfastViewImg;
export const roomMaster = roomMasterImg;
export const bathroom = bathroomImg;
export const mountainClouds = mountainCloudsImg;
